sudo: false
language: python
cache: pip
python:
    - 2.7
    - 3.4
    - 3.5
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -U django flask flask-testing 'selenium!=2.48.0' slimit nose"
    - "pip uninstall ply -y"
    - "pip install ply==3.4"
script: nosetests viceroy/tests/ 
